# Generated by Django 4.1.3 on 2022-11-15 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_out',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
