# Generated by Django 4.1.3 on 2022-11-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_employee_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='First_Name',
        ),
    ]
