# Generated by Django 4.1.3 on 2022-11-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_in_out_in_time_remove_in_out_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_out',
            name='date',
        ),
    ]
