# Generated by Django 4.1.3 on 2022-11-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_firstname_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='First_Name',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='mobile_number',
        ),
    ]
