# Generated by Django 4.1.3 on 2022-11-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_first_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_Name',
            new_name='first_name',
        ),
    ]
