# Generated by Django 4.1.3 on 2022-11-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_first_name_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
