# Generated by Django 4.1.3 on 2022-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
