# Generated by Django 4.1.3 on 2022-12-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_rec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
