# Generated by Django 4.1.3 on 2022-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_employee_face_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='No Department', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='No Position', max_length=200, null=True),
        ),
    ]
